# Generated by Django 5.1.3 on 2024-12-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0004_alter_siteconfig_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='warning',
            field=models.CharField(default='BE CAREFUL IF YOU DELETE THIS SITE CONFIG YOU WILL DELETE EVERYTHING', editable=False, max_length=78),
        ),
    ]
