# Generated by Django 5.1.3 on 2024-12-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0005_siteconfig_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='site_config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_config.siteconfig'),
        ),
    ]
