# Generated by Django 5.1.3 on 2024-12-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0010_alter_menu_site_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Links',
        ),
    ]
