# Generated by Django 5.1.3 on 2024-12-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0012_alter_links_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='default', max_length=78),
        ),
    ]
