# Generated by Django 5.1.3 on 2024-12-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0013_siteconfig_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(max_length=78),
        ),
    ]
