# Generated by Django 5.1.3 on 2024-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0014_alter_siteconfig_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='fav_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
