# Generated by Django 5.1.3 on 2024-12-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0015_siteconfig_fav_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='fav_icon',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='assets/favicon/%Y/%m'),
        ),
    ]
