# Generated by Django 5.1.3 on 2024-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0016_remove_siteconfig_fav_icon_siteconfig_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
