# Generated by Django 5.1.3 on 2024-12-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0017_siteconfig_instagram_siteconfig_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='domain',
            field=models.CharField(blank=True, help_text='Não insira o "https://" apenas o domínio, Exemplo nomedosite.com', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tiktok',
            field=models.URLField(blank=True, help_text='Cole o link completo do perfil, Exemplo: https://www.tiktok.com/@exemplo', null=True),
        ),
    ]
