# Generated by Django 5.1.3 on 2024-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0018_siteconfig_domain_siteconfig_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/footer_logo/%Y/%m'),
        ),
    ]
