# Generated by Django 5.1.3 on 2024-12-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0019_siteconfig_footer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(null=True, upload_to='assets/favicon/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='footer_logo',
            field=models.ImageField(null=True, upload_to='assets/footer_logo/%Y/%m'),
        ),
    ]
