# Generated by Django 5.1.3 on 2024-12-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0020_alter_siteconfig_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='show_pagination',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
