# Generated by Django 5.1.3 on 2024-12-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=70, verbose_name='Titulo da receita')),
                ('ingredients', models.CharField(max_length=278)),
                ('directions', models.TextField(max_length=278)),
                ('preparation_time', models.DurationField(max_length=10)),
                ('difficulty', models.CharField(choices=[('Facil', 'Fácil'), ('Medio', 'Médio'), ('Dificil', 'Difícil')], max_length=7)),
                ('show_recipe', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Register Recipe',
                'verbose_name_plural': 'Register Recipes',
            },
        ),
    ]
