# Generated by Django 5.1.3 on 2024-12-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_tips_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, upload_to='assets/recipe_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(help_text='Separe os passos por virgulas. Exemplo Passo 1, Passo 2, Passo 3', max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Separe os ingredientes por virgulas. Exemplo Cebola, Tomate, Alho', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tips',
            field=models.TextField(blank=True, help_text='Campo não obrigatório', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
    ]
