# Generated by Django 5.1.3 on 2024-12-10 17:15

import utils.time_preparation_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_category_recipe_recipe_image_alter_recipe_directions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(help_text='Exemplos: 30min ou 1h 25min, etc', max_length=9, null=True, validators=[utils.time_preparation_validation.time_validator]),
        ),
    ]
