# Generated by Django 5.1.3 on 2024-12-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_category_category_image_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/category_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(help_text='Separe os passos por duas barras. Exemplo Passo 1 // Passo 2 // Passo 3', max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Separe os ingredientes por duas barras. Exemplo Cebola // Tomate // Alho', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(help_text='Envie imagens como o nome de no MÁXIMO 200 caracteres', max_length=255, upload_to='assets/recipe_images/%Y/%m'),
        ),
    ]
